### ISSUE TITLE
Привет! Это Юрий из Braim, о конкурсе Skolkovo

### ISSUE THREAD

**Issue by Yourun-proger** [HarshBarash/SiriusPython#1]
Привет! Пишу *именно* в этот репо, т.к. тут есть **мой родненький Python**) Хотел спросить над каким  проектом ты работаешь  ***на данный момент*** и есть ли какие-либо задачи для меня?  Могу сказать, что я неплохо пишу на Python.

**Comment by HarshBarash** [comment]
Думаю данные вопросы лучше обсуждать напрямую в дискорде или Telegram)

**Comment by Yourun-proger** [comment]
Написал в Braim
